[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
fastapi = "^0.122.0"
alembic = "^1.17.2"
sqlalchemy = "^2.0.44"
environs = "^14.5.0"
uvicorn = "^0.38.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.6"
black = "^25.11.0"

